### ISSUE TITLE
NotImplementedError: <class 'foliatools.rst2folia.FoLiATranslator'> visiting unknown node type: container

### ISSUE THREAD

**Issue by pirolen** [proycon/foliatools#18]
Encontered this when using piereling for converting Abbyy-produced HTML file ('.htm'), cf.
https://webservices.cls.ru.nl/piereling/a/output/error.log
===
Undefined environment variable: CUSTOMHTML_INDEX
Running pandoc --from=html --to=rst "input/kap1_pp1_2_adobeimgpdf_abbyy.htm.html" > "output/kap1_pp1_2_adobeimgpdf_abbyy.rst"

Running rst2folia --docid="kap1_pp1_2_adobeimgpdf_abbyy" "output/kap1_pp1_2_adobeimgpdf_abbyy.rst" "output/kap1_pp1_2_adobeimgpdf_abbyy.folia.xml"
NotImplementedError: <class 'foliatools.rst2folia.FoLiATranslator'> visiting unknown node type: container

**Comment by proycon** [comment]
Thanks for the report! I implemented a fix that should hopefully resolved this (it's not released or deployed yet, will do so shortly).

**Comment by proycon** [comment]
Released now

**Comment by pirolen** [comment]
Thanks so much! Tried again, now got:

Running rst2folia --docid="kap1_pp1_2_adobeimgpdf_abbyy" "output/kap1_pp1_2_adobeimgpdf_abbyy.rst" "output/kap1_pp1_2_adobeimgpdf_abbyy.folia.xml"
NotImplementedError: <class 'foliatools.rst2folia.FoLiATranslator'> visiting unknown node type: rubric

**Comment by proycon** [comment]
Ok, there was another new element it seems. I fixed this now  (not release or deployed yet). 
I do see various artefacts in the conversion output that are not ideal though.
