### ISSUE TITLE
[foliasplit] Split a FoLiA document into multiple

### ISSUE THREAD

**Issue by proycon** [proycon/foliatools#20]
New: Implement a tool that splits a FoLiA document into multiple, on the basis of:

* specific IDs of structural elements to take as the new roots
* after processing x instances of a particular element (for splitting e.g. every 1000 sentences)
* sections that have associated submetadata, the submetadata will then become the metadata of the new document

**Comment by kosloot** [comment]
Are you thinking of real separate documents? Or splitting in a master document and a bunch of `external` ones?
I think both variants could be useful.

**Comment by proycon** [comment]
This is splitting actual documents yes, not using the ``external`` functionality.

**Comment by proycon** [comment]
Ok, I will take of the "external" mechanism too, you're right that it will be useful and this is the proper place for it. Better solve it well once and for all.

**Comment by proycon** [comment]
May have to do additional testing to see if some performance bottlenecks can be identified and solved.
