### ISSUE TITLE
folia2txt yields empty output on files generated by (newer?) ucto and FoLiA-abby

### ISSUE THREAD

**Issue by pirolen** [proycon/foliatools#24]
Have completely updated LaMachine, and run folia2txt on e.g. [this file](https://github.com/proycon/flat/files/5659888/b1_2_kap4_pp298-1.png.ucto.folia.xml.txt) linked [at the FLAT issue today](https://github.com/proycon/flat/issues/166)
The input was an empty string.

Works fine with other files (e.g. TICCL output).

**Comment by proycon** [comment]
That's because of the non-default text class (OCR), run with ``folia2txt -c OCR`` and it should work.

**Comment by pirolen** [comment]
Aah, thanks! ;-)
