### ISSUE TITLE
folia2html: Command line options for a single file

### ISSUE THREAD

**Issue by pirolen** [proycon/foliatools#27]
Not sure how -o is meant to be used when a single input file is to be converted with folia2html.

Clear:
If I do
`folia2html inputfile1  inputfile2'
both output html files get written in the resp. dirs of the inputfiles.

Just mentioning that I was a bit confused what to do, if I want to convert a single file and write the output html to a file,
because then the above syntax does not work, i.e.
`folia2html inputfile1` must be used with redirection ('>').

I then checked the --help and thought that the -o option would be what I was after, but somehow I might have missed something. 
If I do 
`folia2html inputfile -o target_htmlfile`,
 I get
`ERROR: File or directory not found: -o`
and it seems no conversion takes place.(?)

If I do 
`folia2html inputfile -o` (and nothing else),
then the html file is written to the same dir as the inputfile, but there is also the complaint.
"ERROR: File or directory not found: -o".

**Comment by proycon** [comment]
That looks like a bug in the interface yes the ``-o`` option should have indeed worked as you described. I'll take a look. You can use redirection in the meantime of course.
