### ISSUE TITLE
folia2html: <br> tag not converted

### ISSUE THREAD

**Issue by pirolen** [proycon/foliatools#34]
Seems to me that the `<br>` tag is not converted from the .folia.xml to the .html.

**Comment by proycon** [comment]
Do you have an example? Because when I run folia2html on https://github.com/proycon/folia/blob/master/examples/tests/issue88b.2.5.0.folia.xml , which contains an instance of ``<br/>`` as well, things seem fine:  https://download.anaproy.nl/issue88b.html

**Comment by pirolen** [comment]
Apologies, I confused some of my files/workflows  -- of course the converter works perfectly!
