### ISSUE TITLE
tei2folia failure on CLARIAH files VOC General Missives 

### ISSUE THREAD

**Issue by martinreynaert** [proycon/foliatools#35]
Hi proycon,

I would very much like to convert all 589 TEI files produced by DANS Dirk Roorda from the OCR-ed VOC 'Generale Missiven' (13 volumes)(http://resources.huygens.knaw.nl/retroboeken/generalemissiven/#page=0&accessor=toc&view=homePane)
to FoLiA.

I get the following errors on this one:

https://github.com/Dans-labs/clariah-gm/blob/master/xml/01/p0099.xml

as well as on others from the same source.

I have no idea what is wrong, hope you can help!

Error:

(LMdev) reynaert@violet:FOLIA$ tei2folia p0099.xml 
Instantiating XML parser
Converting p0099.xml
VALIDATION ERROR on full parse by library in p0099.xml
DeclarationError: Encountered an instance without proper declaration: Comment <comment>!
Unable to convert  p0099.xml

Looking forward to your response! Thanks!

Martin

**Comment by proycon** [comment]
Ok, this document converts now, even though the documents aren't really TEI P5 compliant. Could you test it on a few more and see if the conversion output is sane enough?
